#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Gradle start up script for POSIX generated by "Gradle init"
#

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

die () {
    echo
    echo "ERROR: $*"
    echo
    exit 1
} >&2

if ! command -v java >/dev/null 2>&1
then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
fi

JAVA_EXE=$( command -v java ) || exit

# Use JAVA_OPTS if set, otherwise use DEFAULT_JVM_OPTS
if [ -z "$JAVA_OPTS" ]; then
    JVM_OPTS=$DEFAULT_JVM_OPTS
else
    JVM_OPTS=$JAVA_OPTS
fi

exec "$JAVA_EXE" $JVM_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
