#!/bin/sh
##
## Gradle start up script for POSIX generated by "Gradle init"
##

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD=maximum
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

die () {
    echo
    echo "ERROR: $*"
    echo
    exit 1
} >&2

warn () {
    echo "$*"
} >&2

if ! command -v java >/dev/null 2>&1
then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
